load("@root//buck/wasm:defs.bzl", "editor")

editor(
    name = "audio_block",
    deps = [
        "//crates/beui:beui",
        "//crates/block-client:block-client",
        "//crates/block-editor-plugin:block-editor-plugin",
        "//third-party/rust:uuid",
    ],
    module = "audio_block",
    test_deps = [
        "//crates/block-ui-test:block-ui-test",
    ],
)
