buildscript.run = true

[[cxx_library]]
name = "parser"
srcs = [
  "tree-sitter-markdown/src/parser.c",
  "tree-sitter-markdown/src/scanner.c",
  "tree-sitter-markdown-inline/src/parser.c",
  "tree-sitter-markdown-inline/src/scanner.c",
]
headers = ["tree-sitter-markdown/src/**/*.h", "tree-sitter-markdown-inline/src/**/*.h"]
include_paths = ["tree-sitter-markdown/src"]
compiler_flags = ["-std=c11", "-w"]
