[package]
name = "beui-font-freetype"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
beui-core = { path = "../beui-core" }
foldhash = "0.2"
freetype = "0.7"
harfbuzz_rs = "2"
unicode-script = "0.5"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
libloading = "0.8"

[lints]
workspace = true
