load("@root//buck/wasm:defs.bzl", "editor")

editor(
    name = "counter",
    deps = [
        "//crates/beui:beui",
        "//crates/block-client:block-client",
        "//crates/block-editor-plugin:block-editor-plugin",
        "//crates/block-reactive:block-reactive",
        "//third-party/rust:uuid",
    ],
    module = "counter",
    test_deps = [
        "//crates/block-ui-test:block-ui-test",
    ],
)
