load("@root//buck/cargo:defs.bzl", "cargo_example", "cargo_library", "cargo_test")

cargo_library()

cargo_test()

# The examples: `./scripts/buck run //crates/reactive:<example>-example`.

cargo_example("retained")
