use super::*;

mod a_child_block_asks_the_host_for_the_frame_it_will_own;
mod a_docked_editor_hands_its_tabs_to_the_host_as_panes;
mod a_focused_beui_child_gets_the_whole_frame_not_just_its_embedded_rect;
mod a_focused_beui_childs_reported_content_is_its_own_canvas_not_the_whole_view;
mod a_layout_the_host_rearranged_comes_back_as_the_editors_own;
mod a_visible_editor_shows_its_user_as_active;
mod an_open_beui_overlay_is_reported_over_the_child_it_covers;
