[package]
name = "calendar"
edition.workspace = true
version.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
beui = { path = "../../beui", default-features = false, features = ["render"] }
block-ui = { path = "../../block-ui" }
block-editor-plugin = { path = "../../block-editor-plugin" }
uuid = "1"

[dev-dependencies]
block-ui-test = { path = "../../block-ui-test" }

[lints]
workspace = true
