[package]
name = "block-editor-beui"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
be-block = { path = "../be-block" }
beui = { path = "../beui", default-features = false }
beui-adapter-plugin = { path = "../beui-adapter-plugin" }
block-editor-plugin = { path = "../block-editor-plugin" }
block-plugin-api = { path = "../block-plugin-api" }
block-ui = { path = "../block-ui" }
serde_json = "1"
uuid = "1"

[dev-dependencies]
serde = "1"

[lints]
workspace = true
