rust_library(
    name = "block-gpu-guest",
    crate = "block_gpu_guest",
    crate_root = "src/lib.rs",
    deps = select({
        # web-sys is how the browser half reaches its canvas.
        "DEFAULT": [
            "//crates/block-gpu-abi:block-gpu-abi",
            "//third-party/rust:serde",
            "//third-party/rust:wgpu",
        ],
        "prelude//cpu:wasm32": [
            "//crates/block-gpu-abi:block-gpu-abi",
            "//third-party/rust:serde",
            "//third-party/rust:web-sys",
            "//third-party/rust:wgpu",
        ],
    }),
    edition = "2024",
    env = {
        "CARGO_CRATE_NAME": "block_gpu_guest",
        "CARGO_MANIFEST_DIR": "crates/block-gpu-guest",
        "CARGO_PKG_NAME": "block-gpu-guest",
        "CARGO_PKG_VERSION": "0.1.0",
    },
    srcs = glob(["src/**/*.rs"]),
    visibility = ["PUBLIC"],
)

rust_test(
    name = "test",
    crate = "block_gpu_guest",
    crate_root = "src/lib.rs",
    deps = [
        "//crates/block-gpu-abi:block-gpu-abi",
        "//third-party/rust:serde",
        "//third-party/rust:wgpu",
    ],
    edition = "2024",
    env = {
        "CARGO_CRATE_NAME": "block_gpu_guest",
        "CARGO_MANIFEST_DIR": "crates/block-gpu-guest",
        "CARGO_PKG_NAME": "block-gpu-guest",
        "CARGO_PKG_VERSION": "0.1.0",
    },
    srcs = glob(["src/**/*.rs"]),
)
