[package]
name = "block-gpu-guest"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
block-gpu-abi = { path = "../block-gpu-abi" }
serde = { version = "1", features = ["derive"] }
wgpu = { version = "29", default-features = false, features = ["custom", "std", "web", "wgsl"] }

[lints]
workspace = true
