use super::*;

mod a_linear_scale_maps_the_fraction_straight_onto_the_range;
mod a_midpoint_at_the_centre_or_outside_the_range_leaves_the_slider_linear;
mod a_midpoint_scale_maps_a_value_back_to_the_fraction_it_came_from;
mod a_midpoint_scale_puts_its_midpoint_at_the_centre_of_the_track;
mod a_midpoint_scale_spends_more_track_above_the_first_unit_than_below_it;
