use super::*;

mod a_linear_scale_maps_the_fraction_straight_onto_the_range;
mod a_midpoint_outside_the_range_falls_back_to_a_linear_scale;
mod a_midpoint_scale_maps_a_value_back_to_the_fraction_it_came_from;
mod a_midpoint_scale_puts_its_midpoint_at_the_centre_of_the_track;
