rust_library(
    name = "wasi-threads",
    srcs = glob(["src/**/*.rs"]),
    crate = "wasi_threads",
    crate_root = "src/lib.rs",
    edition = "2024",
    env = {
        "CARGO_CRATE_NAME": "wasi_threads",
        "CARGO_MANIFEST_DIR": "crates/wasi-threads",
        "CARGO_PKG_NAME": "wasi-threads",
        "CARGO_PKG_VERSION": "0.1.0",
    },
    visibility = ["PUBLIC"],
)

rust_test(
    name = "test",
    srcs = glob(["src/**/*.rs"]),
    crate = "wasi_threads",
    crate_root = "src/lib.rs",
    edition = "2024",
    env = {
        "CARGO_CRATE_NAME": "wasi_threads",
        "CARGO_MANIFEST_DIR": "crates/wasi-threads",
        "CARGO_PKG_NAME": "wasi-threads",
        "CARGO_PKG_VERSION": "0.1.0",
    },
)
