rust_library(
    name = "reactive_macros",
    srcs = glob(["src/**/*.rs"]),
    crate = "reactive_macros",
    crate_root = "src/lib.rs",
    edition = "2024",
    env = {
        "CARGO_CRATE_NAME": "reactive_macros",
        "CARGO_MANIFEST_DIR": "crates/reactive_macros",
        "CARGO_PKG_NAME": "reactive_macros",
        "CARGO_PKG_VERSION": "0.1.0",
    },
    proc_macro = True,
    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust:proc-macro2",
        "//third-party/rust:quote",
        "//third-party/rust:syn",
    ],
)

rust_test(
    name = "test",
    srcs = glob(["src/**/*.rs"]),
    crate = "reactive_macros",
    crate_root = "src/lib.rs",
    edition = "2024",
    env = {
        "CARGO_CRATE_NAME": "reactive_macros",
        "CARGO_MANIFEST_DIR": "crates/reactive_macros",
        "CARGO_PKG_NAME": "reactive_macros",
        "CARGO_PKG_VERSION": "0.1.0",
    },
    rustc_flags = ["--extern", "proc_macro"],
    deps = [
        "//third-party/rust:proc-macro2",
        "//third-party/rust:quote",
        "//third-party/rust:syn",
    ],
)
