use super::*;

mod fixed_items_use_their_fixed_length;
mod intrinsic_items_use_their_measured_length;
mod percent_items_get_nothing_when_no_space_remains;
mod percent_items_land_on_device_pixels_at_a_fractional_scale;
mod percent_items_measure_intrinsically_without_bounds;
mod percent_items_normalize_when_they_dont_sum_to_100;
mod percent_items_split_an_odd_space_into_whole_pixels;
mod percent_items_split_remaining_space_by_weight;
mod spacing_is_subtracted_before_splitting_percent_items;
