load("@root//buck/wasm:defs.bzl", "editor")

editor(
    name = "workspace_ui",
    deps = [
        "//crates/beui:beui",
        "//crates/block:block",
        "//crates/block-client:block-client",
        "//crates/block-editor-plugin:block-editor-plugin",
        "//third-party/rust:serde_json",
        "//third-party/rust:uuid",
    ],
    module = "workspace_ui",
    test_deps = [
        "//crates/block-ui-test:block-ui-test",
    ],
)
