[package]
name = "scene_3d"
edition.workspace = true
version.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
beui = { path = "../../beui", default-features = false, features = ["render"] }
block-client = { path = "../../block-client" }
block-editor-plugin = { path = "../../block-editor-plugin" }
bytemuck = { version = "1", features = ["derive"] }
uuid = "1"
wgpu = { version = "29", default-features = false, features = ["std", "wgsl"] }

[dev-dependencies]
block-ui-test = { path = "../../block-ui-test" }

[lints]
workspace = true
