[package]
name = "scene_3d"
edition.workspace = true
version.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
block-editor-plugin = { path = "../../block-editor-plugin" }
bytemuck = { version = "1", features = ["derive"] }
uuid = "1"

[lints]
workspace = true
