use block_plugin_api::{EditorInstanceId, EditorRegion};

use super::*;
mod a_painting_drawn_at_another_size_is_cropped_rather_than_stretched;
mod a_translucent_surface_is_blended_once_over_what_is_behind_it;
mod surface_damage_reaches_the_pieces_of_the_screen_it_falls_on;
