load("@root//buck/cargo:defs.bzl", "cargo_binary", "cargo_example", "cargo_library", "cargo_test")

cargo_library()

cargo_test()

cargo_binary()

# The examples: `./scripts/buck run //crates/block-wasm-host:<example>-example`.

cargo_example("instantiate")
