#!/usr/bin/env python3
#
# Resolves the Ubuntu packages a sysroot is made of, and writes them down.
#
# The input is a snapshot of the Ubuntu archive - snapshot.ubuntu.com serves
# the archive as it was at any moment, so a timestamp pins every package index
# for good - and the packages the build asked for. The output is packages.bzl:
# every package in their dependency closure, with the URL, hash and size of its
# .deb, which buck/sysroot/BUCK downloads and lays out. It is checked in, like
# a lockfile, and ./scripts/buckify writes it; guides/buck2.md says how the
# pieces fit.
#
# Resolution is apt's, simplified: Depends and Pre-Depends, the first
# alternative that exists, a virtual package's first provider, and the highest
# version any of the suites has. Recommends are not followed.
#
# Usage:
#   resolve.py SNAPSHOT ARCHITECTURE PACKAGE... > packages.bzl

import json
import lzma
import re
import sys
import urllib.request

SUITES = ["noble", "noble-updates", "noble-security"]
COMPONENTS = ["main", "universe"]


def archive(architecture):
    return "ubuntu" if architecture in ("amd64", "i386") else "ubuntu-ports"


def fetch(url):
    for attempt in range(5):
        try:
            with urllib.request.urlopen(url, timeout=120) as response:
                return response.read()
        except Exception:
            if attempt == 4:
                raise


def stanzas(text):
    for block in text.split("\n\n"):
        fields = {}
        key = None
        for line in block.split("\n"):
            if not line:
                continue
            if line[0] in " \t" and key:
                fields[key] += "\n" + line
                continue
            key, _, value = line.partition(":")
            fields[key] = value.strip()
        if "Package" in fields:
            yield fields


def version_key(version):
    epoch, _, rest = version.rpartition(":")
    upstream, _, revision = rest.rpartition("-") if "-" in rest else (rest, "", "")
    return (int(epoch or 0), _debian_part(upstream), _debian_part(revision or "0"))


def _debian_part(value):
    parts = []
    for text, number in re.findall(r"(\D*)(\d*)", value):
        parts.append(tuple(_character_order(character) for character in text) + (256,))
        parts.append(int(number) if number else 0)
    return tuple(parts)


def _character_order(character):
    if character == "~":
        return -1
    if character.isalpha():
        return ord(character)
    return ord(character) + 256


def main():
    snapshot, architecture = sys.argv[1], sys.argv[2]
    wanted = sys.argv[3:]
    base = "https://snapshot.ubuntu.com/{}/{}".format(archive(architecture), snapshot)

    packages = {}
    for suite in SUITES:
        for component in COMPONENTS:
            url = "{}/dists/{}/{}/binary-{}/Packages.xz".format(base, suite, component, architecture)
            for fields in stanzas(lzma.decompress(fetch(url)).decode()):
                name = fields["Package"]
                if name not in packages or version_key(fields["Version"]) > version_key(packages[name]["Version"]):
                    packages[name] = fields

    providers = {}
    for name, fields in sorted(packages.items()):
        for provided in fields.get("Provides", "").split(","):
            provided = provided.strip().split(" ")[0]
            if provided:
                providers.setdefault(provided, []).append(name)

    chosen = {}
    queue = list(wanted)
    while queue:
        name = queue.pop()
        if name in chosen:
            continue
        if name not in packages:
            sys.exit("{} is not in the snapshot".format(name))
        fields = packages[name]
        chosen[name] = fields
        depends = ", ".join(filter(None, [fields.get("Pre-Depends", ""), fields.get("Depends", "")]))
        for group in filter(None, (group.strip() for group in depends.split(","))):
            alternatives = [re.split(r"[\s(:]", alternative.strip())[0] for alternative in group.split("|")]
            pick = next((alternative for alternative in alternatives if alternative in chosen), None)
            if pick is None:
                pick = next((alternative for alternative in alternatives if alternative in packages), None)
            if pick is None:
                for alternative in alternatives:
                    candidates = providers.get(alternative, [])
                    pick = next((candidate for candidate in candidates if candidate in chosen), None) or (
                        candidates[0] if candidates else None
                    )
                    if pick:
                        break
            if pick is None:
                sys.exit("nothing in the snapshot satisfies '{}', which {} depends on".format(group, name))
            queue.append(pick)

    print("# @generated by ./scripts/buckify from buck/sysroot/BUCK. Do not edit by hand:")
    print("# buck/sysroot/resolve.py writes it.")
    print("")
    print("packages = [")
    for name in sorted(chosen):
        fields = chosen[name]
        print("    ({}, {}, {}, {}),".format(
            json.dumps(name),
            json.dumps("{}/{}".format(base, fields["Filename"])),
            json.dumps(fields["SHA256"]),
            int(fields["Size"]),
        ))
    print("]")


main()
