rust_library(
    name = "be-graph",
    crate = "be_graph",
    crate_root = "src/lib.rs",
    deps = [
        "//crates/be-commit:be-commit",
        "//crates/be-store:be-store",
        "//third-party/rust:serde",
        "//third-party/rust:uuid",
    ],
    edition = "2024",
    env = {
        "CARGO_CRATE_NAME": "be_graph",
        "CARGO_MANIFEST_DIR": "crates/be-graph",
        "CARGO_PKG_NAME": "be-graph",
        "CARGO_PKG_VERSION": "0.1.0",
    },
    srcs = glob(["src/**/*.rs"]),
    visibility = ["PUBLIC"],
)

rust_test(
    name = "test",
    crate = "be_graph",
    crate_root = "src/lib.rs",
    deps = [
        "//crates/be-commit:be-commit",
        "//crates/be-store:be-store",
        "//third-party/rust:serde",
        "//third-party/rust:uuid",
    ],
    edition = "2024",
    env = {
        "CARGO_CRATE_NAME": "be_graph",
        "CARGO_MANIFEST_DIR": "crates/be-graph",
        "CARGO_PKG_NAME": "be-graph",
        "CARGO_PKG_VERSION": "0.1.0",
    },
    srcs = glob(["src/**/*.rs"]),
)
