[package]
name = "beui-inspector"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
accesskit = "0.24.1"
beui-components-styled = { path = "../beui-components-styled" }
beui-components-unstyled = { path = "../beui-components-unstyled" }
beui-core = { path = "../beui-core" }
beui-view = { path = "../beui-view" }
beui_macros = { path = "../beui-macros" }
reactive = { path = "../reactive" }

[lints]
workspace = true
