use std::cmp::Ordering;
use std::collections::{BTreeMap, HashMap};
use std::process::ExitCode;

use crate::starlark::quote;

pub fn run(arguments: &[String]) -> Result<ExitCode, String> {
    let [base, indexes, sets @ ..] = arguments else {
        return Err(
            "usage: resolve BASE_URL INDEX_DIR NAME:ARCHITECTURE:PACKAGE[,PACKAGE...]...".into(),
        );
    };
    let mut out = String::from(
        "# @generated by ./scripts/bazel run //:lock-sysroot from bazel/sysroot/wanted.bzl. Do not edit\n\
         # by hand: crates/bazel-tools resolves it.\n\npackages = {\n",
    );
    for set in sets {
        let mut parts = set.splitn(3, ':');
        let (Some(name), Some(architecture), Some(wanted)) =
            (parts.next(), parts.next(), parts.next())
        else {
            return Err(format!("{set} is not NAME:ARCHITECTURE:PACKAGES"));
        };
        let packages = load(&format!("{indexes}/{architecture}"))?;
        let wanted: Vec<&str> = wanted.split(',').collect();
        out.push_str(&format!("    {}: [\n", quote(name)));
        for (package, fields) in resolve(&packages, &wanted)? {
            out.push_str(&format!(
                "        ({}, {}, {}, {}),\n",
                quote(package),
                quote(&format!("{base}/{}", field(fields, "Filename"))),
                quote(field(fields, "SHA256")),
                field(fields, "Size")
                    .parse::<u64>()
                    .map_err(|error| format!("{package}: {error}"))?,
            ));
        }
        out.push_str("    ],\n");
    }
    out.push_str("}\n");
    print!("{out}");
    Ok(ExitCode::SUCCESS)
}

type Fields = HashMap<String, String>;

fn field<'a>(fields: &'a Fields, key: &str) -> &'a str {
    fields.get(key).map(String::as_str).unwrap_or_default()
}

fn load(directory: &str) -> Result<BTreeMap<String, Fields>, String> {
    let mut files: Vec<_> = std::fs::read_dir(directory)
        .map_err(|error| format!("{directory}: {error}"))?
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .collect();
    files.sort();
    let mut packages: BTreeMap<String, Fields> = BTreeMap::new();
    for file in files {
        let text = std::fs::read_to_string(&file)
            .map_err(|error| format!("{}: {error}", file.display()))?;
        for fields in stanzas(&text) {
            let name = field(&fields, "Package").to_owned();
            let newer = packages.get(&name).is_none_or(|known| {
                compare_versions(field(&fields, "Version"), field(known, "Version"))
                    == Ordering::Greater
            });
            if newer {
                packages.insert(name, fields);
            }
        }
    }
    Ok(packages)
}

pub fn stanzas(text: &str) -> Vec<Fields> {
    let mut found = Vec::new();
    for block in text.split("\n\n") {
        let mut fields = Fields::new();
        let mut key: Option<String> = None;
        for line in block.split('\n') {
            if line.is_empty() {
                continue;
            }
            if line.starts_with([' ', '\t'])
                && let Some(key) = &key
            {
                let value = fields.entry(key.clone()).or_default();
                value.push('\n');
                value.push_str(line);
                continue;
            }
            let (name, value) = line.split_once(':').unwrap_or((line, ""));
            fields.insert(name.to_owned(), value.trim().to_owned());
            key = Some(name.to_owned());
        }
        if fields.contains_key("Package") {
            found.push(fields);
        }
    }
    found
}

fn resolve<'a>(
    packages: &'a BTreeMap<String, Fields>,
    wanted: &[&str],
) -> Result<BTreeMap<&'a str, &'a Fields>, String> {
    let mut providers: HashMap<&str, Vec<&str>> = HashMap::new();
    for (name, fields) in packages {
        for provided in field(fields, "Provides").split(',') {
            let provided = provided.trim().split(' ').next().unwrap_or_default();
            if !provided.is_empty() {
                providers.entry(provided).or_default().push(name);
            }
        }
    }

    let mut chosen: BTreeMap<&str, &Fields> = BTreeMap::new();
    let mut queue: Vec<String> = wanted.iter().map(|name| (*name).to_owned()).collect();
    while let Some(name) = queue.pop() {
        if chosen.contains_key(name.as_str()) {
            continue;
        }
        let Some((name, fields)) = packages.get_key_value(&name) else {
            return Err(format!("{name} is not in the snapshot"));
        };
        chosen.insert(name, fields);
        let depends: Vec<&str> = [field(fields, "Pre-Depends"), field(fields, "Depends")]
            .into_iter()
            .filter(|value| !value.is_empty())
            .collect();
        let depends = depends.join(", ");
        for group in depends
            .split(',')
            .map(str::trim)
            .filter(|group| !group.is_empty())
        {
            let alternatives: Vec<&str> = group
                .split('|')
                .map(|alternative| {
                    alternative
                        .trim()
                        .split(|c: char| c.is_whitespace() || c == '(' || c == ':')
                        .next()
                        .unwrap_or_default()
                })
                .collect();
            let mut pick = alternatives
                .iter()
                .find(|alternative| chosen.contains_key(**alternative))
                .copied();
            if pick.is_none() {
                pick = alternatives
                    .iter()
                    .find(|alternative| packages.contains_key(**alternative))
                    .copied();
            }
            if pick.is_none() {
                for alternative in &alternatives {
                    let candidates = providers
                        .get(alternative)
                        .map(Vec::as_slice)
                        .unwrap_or_default();
                    pick = candidates
                        .iter()
                        .find(|candidate| chosen.contains_key(**candidate))
                        .or(candidates.first())
                        .copied();
                    if pick.is_some() {
                        break;
                    }
                }
            }
            let Some(pick) = pick else {
                return Err(format!(
                    "nothing in the snapshot satisfies '{group}', which {name} depends on"
                ));
            };
            queue.push(pick.to_owned());
        }
    }
    Ok(chosen)
}

pub fn compare_versions(left: &str, right: &str) -> Ordering {
    version_key(left).cmp(&version_key(right))
}

type Part = Vec<(Vec<i32>, u128)>;

fn version_key(version: &str) -> (u128, Part, Part) {
    let (epoch, rest) = version.rsplit_once(':').unwrap_or(("", version));
    let (upstream, revision) = rest.rsplit_once('-').unwrap_or((rest, ""));
    let revision = if revision.is_empty() { "0" } else { revision };
    (
        epoch.parse().unwrap_or(0),
        debian_part(upstream),
        debian_part(revision),
    )
}

fn debian_part(value: &str) -> Part {
    let characters: Vec<char> = value.chars().collect();
    let mut parts = Vec::new();
    let mut index = 0;
    while index < characters.len() {
        let mut text = Vec::new();
        while index < characters.len() && !characters[index].is_ascii_digit() {
            text.push(character_order(characters[index]));
            index += 1;
        }
        text.push(256);
        let mut number = 0u128;
        while index < characters.len() && characters[index].is_ascii_digit() {
            number = number * 10 + u128::from(characters[index].to_digit(10).unwrap_or(0));
            index += 1;
        }
        parts.push((text, number));
    }
    parts.push((vec![256], 0));
    parts
}

fn character_order(character: char) -> i32 {
    if character == '~' {
        -1
    } else if character.is_alphabetic() {
        character as i32
    } else {
        character as i32 + 256
    }
}
