rust_library(
    name = "block-ui-test",
    srcs = glob(["src/**/*.rs"]),
    crate = "block_ui_test",
    crate_root = "src/lib.rs",
    edition = "2024",
    env = {
        "CARGO_CRATE_NAME": "block_ui_test",
        "CARGO_MANIFEST_DIR": "crates/block-ui-test",
        "CARGO_PKG_NAME": "block-ui-test",
        "CARGO_PKG_VERSION": "0.1.0",
    },
    visibility = ["PUBLIC"],
    deps = [
        "//crates/beui:beui",
        "//crates/block-editor-plugin:block-editor-plugin",
        "//crates/paint-snapshot:paint-snapshot",
        "//third-party/rust:egui",
        "//third-party/rust:egui_kittest",
        "//third-party/rust:uuid",
    ],
)

rust_test(
    name = "test",
    srcs = glob(["src/**/*.rs"]),
    crate = "block_ui_test",
    crate_root = "src/lib.rs",
    edition = "2024",
    env = {
        "CARGO_CRATE_NAME": "block_ui_test",
        "CARGO_MANIFEST_DIR": "crates/block-ui-test",
        "CARGO_PKG_NAME": "block-ui-test",
        "CARGO_PKG_VERSION": "0.1.0",
    },
    deps = [
        "//crates/beui:beui",
        "//crates/block-client:block-client",
        "//crates/block-editor-plugin:block-editor-plugin",
        "//crates/paint-snapshot:paint-snapshot",
        "//third-party/rust:egui",
        "//third-party/rust:egui_kittest",
        "//third-party/rust:uuid",
    ],
)
