[package]
name = "block-ui-test"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
beui = { path = "../beui", default-features = false }
block-editor-beui = { path = "../block-editor-beui" }
paint-snapshot = { path = "../paint-snapshot" }
uuid = "1"

[dev-dependencies]

[lints]
workspace = true
