load("@root//buck/wasm:defs.bzl", "editor")

editor(
    name = "database_schema",
    deps = [
        "//crates/beui:beui",
        "//crates/block-client:block-client",
        "//crates/block-editor-plugin:block-editor-plugin",
        "//third-party/rust:uuid",
    ],
    module = "database_schema",
)
