[package]
name = "database_schema"
edition.workspace = true
version.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
beui = { path = "../../beui", default-features = false, features = ["render"] }
block-editor-beui = { path = "../../block-editor-beui" }
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
block-ui-test = { path = "../../block-ui-test" }

[lints]
workspace = true
