rust_library(
    name = "text-editor-core",
    srcs = glob(["src/**/*.rs"]),
    crate = "text_editor_core",
    crate_root = "src/lib.rs",
    edition = "2024",
    env = {
        "CARGO_CRATE_NAME": "text_editor_core",
        "CARGO_MANIFEST_DIR": "crates/text-editor-core",
        "CARGO_PKG_NAME": "text-editor-core",
        "CARGO_PKG_VERSION": "0.1.0",
    },
    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust:serde",
        "//third-party/rust:similar",
        "//third-party/rust:tree-sitter",
        "//third-party/rust:tree-sitter-md",
        "//third-party/rust:tree-sitter-rust",
        "//third-party/rust:tree-sitter-zig",
        "//third-party/rust:unicode-segmentation",
        "//third-party/rust:uuid",
    ],
)

rust_test(
    name = "test",
    srcs = glob(["src/**/*.rs"]),
    crate = "text_editor_core",
    crate_root = "src/lib.rs",
    edition = "2024",
    env = {
        "CARGO_CRATE_NAME": "text_editor_core",
        "CARGO_MANIFEST_DIR": "crates/text-editor-core",
        "CARGO_PKG_NAME": "text-editor-core",
        "CARGO_PKG_VERSION": "0.1.0",
    },
    deps = [
        "//third-party/rust:serde",
        "//third-party/rust:serde_json",
        "//third-party/rust:similar",
        "//third-party/rust:tree-sitter",
        "//third-party/rust:tree-sitter-md",
        "//third-party/rust:tree-sitter-rust",
        "//third-party/rust:tree-sitter-zig",
        "//third-party/rust:unicode-segmentation",
        "//third-party/rust:uuid",
    ],
)
