[package]
name = "beui-demo"
edition.workspace = true
version.workspace = true
license.workspace = true

[[bin]]
name = "demo"
path = "src/main.rs"

[dependencies]
beui = { path = "../beui", default-features = false }
beui_macros = { path = "../beui-macros" }
text-editor-core = { path = "../text-editor-core" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
beui = { path = "../beui" }

[dev-dependencies]
block-ui-test = { path = "../block-ui-test" }

[lints]
workspace = true
