export_file(
    name = "stage.sh",
    visibility = ["PUBLIC"],
)

export_file(
    name = "smoke.sh",
    visibility = ["PUBLIC"],
)

export_file(
    name = "dev.sh",
    visibility = ["PUBLIC"],
)

export_file(
    name = "web-dev.sh",
    visibility = ["PUBLIC"],
)

export_file(
    name = "web-drive.mjs",
    visibility = ["PUBLIC"],
)
