load("@root//buck/cargo:defs.bzl", "cargo_library", "cargo_test", "editor_packages")

cargo_library()

# every_editor_manifest_parses reads each editor's manifest.json from
# EDITOR_MANIFESTS, a directory of <editor>/manifest.json, so that the
# manifests are inputs of the test like any other and it runs on a worker.
filegroup(
    name = "editor_manifests",
    srcs = {"{}/manifest.json".format(package.split("/")[-1]): "//{}:manifest".format(package) for package in editor_packages()},
)

cargo_test(
    env = {"EDITOR_MANIFESTS": "$(location :editor_manifests)"},
)
