rust_library(
    name = "block-plugin-api",
    crate = "block_plugin_api",
    crate_root = "src/lib.rs",
    deps = select({
        # No libc on a guest.
        "DEFAULT": [
            "//third-party/rust:bincode",
            "//third-party/rust:libc",
            "//third-party/rust:serde",
            "//third-party/rust:serde_json",
            "//third-party/rust:uuid",
        ],
        "prelude//cpu:wasm32": [
            "//third-party/rust:bincode",
            "//third-party/rust:serde",
            "//third-party/rust:serde_json",
            "//third-party/rust:uuid",
        ],
    }),
    edition = "2024",
    env = {
        "CARGO_CRATE_NAME": "block_plugin_api",
        "CARGO_MANIFEST_DIR": "crates/block-plugin-api",
        "CARGO_PKG_NAME": "block-plugin-api",
        "CARGO_PKG_VERSION": "0.1.0",
    },
    srcs = glob(["src/**/*.rs"]),
    visibility = ["PUBLIC"],
)

rust_test(
    name = "test",
    crate = "block_plugin_api",
    crate_root = "src/lib.rs",
    deps = [
        "//third-party/rust:bincode",
        "//third-party/rust:libc",
        "//third-party/rust:serde",
        "//third-party/rust:serde_json",
        "//third-party/rust:uuid",
    ],
    edition = "2024",
    env = {
        "CARGO_CRATE_NAME": "block_plugin_api",
        "CARGO_MANIFEST_DIR": "crates/block-plugin-api",
        "CARGO_PKG_NAME": "block-plugin-api",
        "CARGO_PKG_VERSION": "0.1.0",
    },
    labels = ["cargo-only"],
    srcs = glob(["src/**/*.rs"]),
)
