
rust_binary(
    name = "plugin-test-runner-bin",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/main.rs",
    edition = "2024",
    env = {
        "CARGO_CRATE_NAME": "plugin_test_runner",
        "CARGO_MANIFEST_DIR": "crates/plugin-test-runner",
        "CARGO_PKG_NAME": "plugin-test-runner",
        "CARGO_PKG_VERSION": "0.1.0",
    },
    visibility = ["PUBLIC"],
    deps = [
        "//crates/block-wasm-host:block-wasm-host",
        "//third-party/rust:pollster",
        "//third-party/rust:wgpu",
    ],
)
