rust_library(
    name = "be-store",
    srcs = glob(["src/**/*.rs"]),
    crate = "be_store",
    crate_root = "src/lib.rs",
    edition = "2024",
    env = {
        "CARGO_CRATE_NAME": "be_store",
        "CARGO_MANIFEST_DIR": "crates/be-store",
        "CARGO_PKG_NAME": "be-store",
        "CARGO_PKG_VERSION": "0.1.0",
    },
    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust:chacha20poly1305",
        "//third-party/rust:postcard",
        "//third-party/rust:rand",
        "//third-party/rust:serde",
        "//third-party/rust:sha2",
        "//third-party/rust:uuid",
    ],
)

rust_test(
    name = "test",
    srcs = glob(["src/**/*.rs"]),
    crate = "be_store",
    crate_root = "src/lib.rs",
    edition = "2024",
    env = {
        "CARGO_CRATE_NAME": "be_store",
        "CARGO_MANIFEST_DIR": "crates/be-store",
        "CARGO_PKG_NAME": "be-store",
        "CARGO_PKG_VERSION": "0.1.0",
    },
    deps = [
        "//third-party/rust:chacha20poly1305",
        "//third-party/rust:postcard",
        "//third-party/rust:rand",
        "//third-party/rust:serde",
        "//third-party/rust:sha2",
        "//third-party/rust:uuid",
    ],
)
