[package]
name = "be-protocol"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
be-commit = { path = "../be-commit" }
be-graph = { path = "../be-graph" }
be-store = { path = "../be-store" }
postcard = { version = "1", features = ["use-std"] }
serde = { version = "1", features = ["derive"] }
serde_bytes = "0.11"
uuid = { version = "1", features = ["serde", "v4"] }

[lints]
workspace = true
