[package]
name = "text_block"
edition.workspace = true
version.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
beui = { path = "../../beui", default-features = false, features = ["render"] }
block-editor-plugin = { path = "../../block-editor-plugin" }
serde = { version = "1", features = ["derive"] }
similar = "3.1"
text-editor-core = { path = "../../text-editor-core" }
uuid = "1"

[dev-dependencies]
block-ui-test = { path = "../../block-ui-test" }

[lints]
workspace = true
