[package]
name = "beui-adapter-winit"
edition.workspace = true
version.workspace = true
license.workspace = true

[target.'cfg(not(any(target_os = "android", target_arch = "wasm32")))'.dependencies]
accesskit = "0.24.1"
accesskit_winit = "0.33.2"
beui-core = { path = "../beui-core" }
beui-renderer-wgpu = { path = "../beui-renderer-wgpu" }
pollster = "0.4"
wgpu = "29"
winit = "0.30"

[target.'cfg(not(any(target_os = "android", target_os = "ios", target_arch = "wasm32")))'.dependencies]
arboard = { version = "3.6", default-features = false }

[lints]
workspace = true
