load("@root//buck/cargo:defs.bzl", "cargo_example", "cargo_library", "cargo_test")

beui_srcs = glob(["src/**/*.rs", "examples/**/*.rs"])

cargo_library(srcs = beui_srcs)

cargo_test(srcs = beui_srcs)

# The examples: `./scripts/buck run //crates/beui:<example>-example`.

cargo_example("counter", srcs = beui_srcs)

cargo_example("demo", srcs = beui_srcs)

cargo_example("dock", srcs = beui_srcs)

cargo_example("survey", srcs = beui_srcs)
