[package]
name = "beui-adapter-drm"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
be-dmabuf = { path = "../be-dmabuf" }
beui = { path = "../beui", default-features = false, features = ["render"] }
bytemuck = { version = "1", features = ["derive"] }
smithay = { version = "0.7", default-features = false, features = ["backend_drm", "backend_gbm", "backend_libinput", "backend_session_libseat", "backend_udev"] }
wgpu = { version = "29", default-features = false, features = ["vulkan"] }

[lints]
workspace = true
