[package]
name = "beui-view"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
accesskit = "0.24.1"
beui-core = { path = "../beui-core" }
beui-tree = { path = "../beui-tree" }
beui_macros = { path = "../beui-macros" }
reactive = { path = "../reactive" }

[lints]
workspace = true
