use super::*;

mod a_group_cannot_be_dropped_inside_itself;
mod a_group_left_with_one_tab_becomes_that_tab_again;
mod a_pane_holding_only_a_group_takes_the_tabs_of_the_group;
mod a_split_divides_its_area_between_the_panes_and_the_handle;
mod a_tab_dropped_on_another_tab_bar_lands_at_the_place_it_was_dropped;
mod closing_the_last_tab_of_a_window_closes_the_window;
mod dropping_a_tab_onto_another_tab_groups_them;
mod emptying_a_pane_gives_its_room_to_the_pane_it_was_split_from;
mod focusing_a_window_raises_it_over_the_windows_it_overlaps;
mod replacing_a_tab_leaves_it_where_it_was;
mod showing_a_tab_inside_a_group_selects_the_group;
mod splitting_a_tab_with_the_next_makes_a_group_holding_a_split_view;
mod ungrouping_puts_the_tabs_back_where_the_group_was;
