# What an APK is made with, pinned by hash and size: a JDK (javac, d8,
# apksigner), the SDK build tools (aapt2, zipalign), the platform (android.jar)
# and the platform tools (adb, for installing).

jdk_version = "21.0.12.1+1"

http_archive(
    name = "jdk",
    sha256 = "ce79869e1307ed8ee1e2baa86a412b1eb5b75d10a01006d788a6f968bcfaee94",
    size_bytes = 207473347,
    strip_prefix = "jdk-" + jdk_version,
    urls = [
        "https://github.com/adoptium/temurin21-binaries/releases/download/jdk-{}/OpenJDK21U-jdk_x64_linux_hotspot_{}.tar.gz".format(
            jdk_version.replace("+", "%2B"),
            jdk_version.replace("+", "_"),
        )
    ],
    visibility = ["PUBLIC"],
)

http_archive(
    name = "build-tools",
    sha256 = "bd3a4966912eb8b30ed0d00b0cda6b6543b949d5ffe00bea54c04c81e1561d88",
    size_bytes = 61958799,
    strip_prefix = "android-15",
    urls = ["https://dl.google.com/android/repository/build-tools_r35_linux.zip"],
    visibility = ["PUBLIC"],
)

http_archive(
    name = "platform",
    sha256 = "0988cacad01b38a18a47bac14a0695f246bc76c1b06c0eeb8eb0dc825ab0c8e0",
    size_bytes = 64273788,
    strip_prefix = "android-35",
    urls = ["https://dl.google.com/android/repository/platform-35_r02.zip"],
    visibility = ["PUBLIC"],
)

http_archive(
    name = "platform-tools",
    sha256 = "d230f13842f60f782a8645f9c813f8f845bf36089ea7289f28c48f17979313f1",
    size_bytes = 9054187,
    strip_prefix = "platform-tools",
    urls = ["https://dl.google.com/android/repository/platform-tools_r37.0.1-linux.zip"],
    visibility = ["PUBLIC"],
)

# GameActivity's Java half and what it needs at run time: AppCompat, which it
# extends, and androidx.core, whose Insets its native half looks up by name.
# The closure Gradle would resolve for androidx.games:games-activity:4.4.0 (the
# release android-activity's bundled C matches) and androidx.appcompat:appcompat,
# with kotlin-stdlib-jdk7/jdk8 raised to kotlin-stdlib's version, as Gradle's
# module metadata does, so their classes are not defined twice.
maven_artifacts = {
    "activity-1.8.0.aar": (
        "https://dl.google.com/android/maven2/androidx/activity/activity/1.8.0/activity-1.8.0.aar",
        "d3a676709dea04f2a8506e2ae85052fff763db526ac7f16b04de50fdd05b0720",
        169615,
    ),
    "annotation-1.6.0.jar": (
        "https://dl.google.com/android/maven2/androidx/annotation/annotation/1.6.0/annotation-1.6.0.jar",
        "fbc64f5c44a7added8b6eab517cf7d70555e25153bf5d44a6ed9b0e5312f7de9",
        670,
    ),
    "annotation-experimental-1.4.0.aar": (
        "https://dl.google.com/android/maven2/androidx/annotation/annotation-experimental/1.4.0/annotation-experimental-1.4.0.aar",
        "c6eb7e676011ec65b32428373d450debdfc45179c4f8b3a752174fb87c17b08a",
        39811,
    ),
    "annotations-13.0.jar": (
        "https://repo1.maven.org/maven2/org/jetbrains/annotations/13.0/annotations-13.0.jar",
        "ace2a10dc8e2d5fd34925ecac03e4988b2c0f851650c94b8cef49ba1bd111478",
        17536,
    ),
    "appcompat-1.7.1.aar": (
        "https://dl.google.com/android/maven2/androidx/appcompat/appcompat/1.7.1/appcompat-1.7.1.aar",
        "2ad334a323b28046e89b738c77d184cb3dcca32a551ab048851b2fda23a3ba26",
        1148656,
    ),
    "appcompat-resources-1.7.1.aar": (
        "https://dl.google.com/android/maven2/androidx/appcompat/appcompat-resources/1.7.1/appcompat-resources-1.7.1.aar",
        "8e2db31224ca53b108c784da2b361959062716d416b210cfef3d5a3828306df0",
        63997,
    ),
    "collection-1.1.0.jar": (
        "https://dl.google.com/android/maven2/androidx/collection/collection/1.1.0/collection-1.1.0.jar",
        "632a0e5407461de774409352940e292a291037724207a787820c77daf7d33b72",
        42953,
    ),
    "concurrent-futures-1.1.0.jar": (
        "https://dl.google.com/android/maven2/androidx/concurrent/concurrent-futures/1.1.0/concurrent-futures-1.1.0.jar",
        "0ce067c514a0d1049d1bebdf709e344ed3266fe9744275682937cdcb13334e9e",
        25987,
    ),
    "core-1.13.0.aar": (
        "https://dl.google.com/android/maven2/androidx/core/core/1.13.0/core-1.13.0.aar",
        "1b96c8eb10c4b40283fdd6e9aa74ffff05fae4f15d54f61ba69d517fcd144695",
        1270405,
    ),
    "core-common-2.2.0.jar": (
        "https://dl.google.com/android/maven2/androidx/arch/core/core-common/2.2.0/core-common-2.2.0.jar",
        "65308a06b1c00ee186cb9e19321383f043b993813f1522c47f4a3e3303bdba41",
        11657,
    ),
    "core-ktx-1.13.0.aar": (
        "https://dl.google.com/android/maven2/androidx/core/core-ktx/1.13.0/core-ktx-1.13.0.aar",
        "59c54e6129e9261c6d810f8eea4a6ee2f4994d8162b1cd9fc88c9c84c92accfc",
        171581,
    ),
    "core-runtime-2.2.0.aar": (
        "https://dl.google.com/android/maven2/androidx/arch/core/core-runtime/2.2.0/core-runtime-2.2.0.aar",
        "a1be5e0caa2b07623862af6ae21b3ab0718123245184d0e30dea81b53f990a47",
        7577,
    ),
    "cursoradapter-1.0.0.aar": (
        "https://dl.google.com/android/maven2/androidx/cursoradapter/cursoradapter/1.0.0/cursoradapter-1.0.0.aar",
        "a81c8fe78815fa47df5b749deb52727ad11f9397da58b16017f4eb2c11e28564",
        10591,
    ),
    "customview-1.0.0.aar": (
        "https://dl.google.com/android/maven2/androidx/customview/customview/1.0.0/customview-1.0.0.aar",
        "20e5b8f6526a34595a604f56718da81167c0b40a7a94a57daa355663f2594df2",
        33238,
    ),
    "drawerlayout-1.0.0.aar": (
        "https://dl.google.com/android/maven2/androidx/drawerlayout/drawerlayout/1.0.0/drawerlayout-1.0.0.aar",
        "9402442cdc5a43cf62fb14f8cf98c63342d4d9d9b805c8033c6cf7e802749ac1",
        32470,
    ),
    "emoji2-1.3.0.aar": (
        "https://dl.google.com/android/maven2/androidx/emoji2/emoji2/1.3.0/emoji2-1.3.0.aar",
        "2bf23818b23a996ddaa1b5fd5bb32129daff6bbb2dce15166e2fccdd2010b1a5",
        143474,
    ),
    "emoji2-views-helper-1.2.0.aar": (
        "https://dl.google.com/android/maven2/androidx/emoji2/emoji2-views-helper/1.2.0/emoji2-views-helper-1.2.0.aar",
        "7ffa4d464d9db259fca0cdb50fbd4ab63d6872bcda59468b9f7555504c7d5ac4",
        21917,
    ),
    "fragment-1.5.4.aar": (
        "https://dl.google.com/android/maven2/androidx/fragment/fragment/1.5.4/fragment-1.5.4.aar",
        "bc3c2431dda42e94bb9511c587eae890d276e4aafe393a8da7b00169186dafde",
        337572,
    ),
    "games-activity-4.4.0.aar": (
        "https://dl.google.com/android/maven2/androidx/games/games-activity/4.4.0/games-activity-4.4.0.aar",
        "3a8b0887ac55a0a6ab56021ced7353a250539eac811278b74bccd8a5b678d9c9",
        1835961,
    ),
    "interpolator-1.0.0.aar": (
        "https://dl.google.com/android/maven2/androidx/interpolator/interpolator/1.0.0/interpolator-1.0.0.aar",
        "33193135a64fe21fa2c35eec6688f1a76e512606c0fc83dc1b689e37add7732a",
        7669,
    ),
    "kotlin-stdlib-1.8.22.jar": (
        "https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.8.22/kotlin-stdlib-1.8.22.jar",
        "03a5c3965cc37051128e64e46748e394b6bd4c97fa81c6de6fc72bfd44e3421b",
        1670469,
    ),
    "kotlin-stdlib-common-1.8.22.jar": (
        "https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-common/1.8.22/kotlin-stdlib-common-1.8.22.jar",
        "d0c2365e2437ef70f34586d50f055743f79716bcfe65e4bc7239cdd2669ef7c5",
        221491,
    ),
    "kotlin-stdlib-jdk7-1.8.22.jar": (
        "https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.8.22/kotlin-stdlib-jdk7-1.8.22.jar",
        "055f5cb24287fa106100995a7b47ab92126b81e832e875f5fa2cf0bd55693d0b",
        963,
    ),
    "kotlin-stdlib-jdk8-1.8.22.jar": (
        "https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.8.22/kotlin-stdlib-jdk8-1.8.22.jar",
        "4198b0eaf090a4f25b6f7e5a59581f4314ba8c9f6cd1d13ee9d348e65ed8f707",
        969,
    ),
    "kotlinx-coroutines-android-1.6.4.jar": (
        "https://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-coroutines-android/1.6.4/kotlinx-coroutines-android-1.6.4.jar",
        "3fdc0eed5bc4b83ee9622774520a2db25470370eacd1581cac1e37704f095b00",
        19520,
    ),
    "kotlinx-coroutines-core-jvm-1.6.4.jar": (
        "https://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-coroutines-core-jvm/1.6.4/kotlinx-coroutines-core-jvm-1.6.4.jar",
        "c24c8bb27bb320c4a93871501a7e5e0c61607638907b197aef675513d4c820be",
        1476653,
    ),
    "lifecycle-common-2.6.2.jar": (
        "https://dl.google.com/android/maven2/androidx/lifecycle/lifecycle-common/2.6.2/lifecycle-common-2.6.2.jar",
        "f34831b6c71cd844e1d35d1be49d5e79447c5ab856346531b1e8676fda7374b1",
        52314,
    ),
    "lifecycle-livedata-2.0.0.aar": (
        "https://dl.google.com/android/maven2/androidx/lifecycle/lifecycle-livedata/2.0.0/lifecycle-livedata-2.0.0.aar",
        "c82609ced8c498f0a701a30fb6771bb7480860daee84d82e0a81ee86edf7ba39",
        9431,
    ),
    "lifecycle-livedata-core-2.6.1.aar": (
        "https://dl.google.com/android/maven2/androidx/lifecycle/lifecycle-livedata-core/2.6.1/lifecycle-livedata-core-2.6.1.aar",
        "2256780a3cff4a1e57fbb3d442557c17dc363ab8af105bcaf5261d8e2d5db949",
        11345,
    ),
    "lifecycle-process-2.4.1.aar": (
        "https://dl.google.com/android/maven2/androidx/lifecycle/lifecycle-process/2.4.1/lifecycle-process-2.4.1.aar",
        "db649b3efa24e31052145310b002db91da346b3f89c093ec38c3046db45e794e",
        9331,
    ),
    "lifecycle-runtime-2.6.2.aar": (
        "https://dl.google.com/android/maven2/androidx/lifecycle/lifecycle-runtime/2.6.2/lifecycle-runtime-2.6.2.aar",
        "4867fd5279742fba8388821930cb2affe06d81a52814e7e41e70392ea0ef887c",
        21738,
    ),
    "lifecycle-viewmodel-2.6.1.aar": (
        "https://dl.google.com/android/maven2/androidx/lifecycle/lifecycle-viewmodel/2.6.1/lifecycle-viewmodel-2.6.1.aar",
        "e4ff4338999e1c6c9c724719f5d4aa7dd61bf6f545d5256a27a9d375df9f2330",
        39793,
    ),
    "lifecycle-viewmodel-savedstate-2.6.1.aar": (
        "https://dl.google.com/android/maven2/androidx/lifecycle/lifecycle-viewmodel-savedstate/2.6.1/lifecycle-viewmodel-savedstate-2.6.1.aar",
        "c82f89221adbe19df7c7adbab63f4ecc857fc746e3c9494256ab8fa5c20491b2",
        39559,
    ),
    "listenablefuture-1.0.jar": (
        "https://repo1.maven.org/maven2/com/google/guava/listenablefuture/1.0/listenablefuture-1.0.jar",
        "e4ad7607e5c0477c6f890ef26a49cb8d1bb4dffb650bab4502afee64644e3069",
        3149,
    ),
    "loader-1.0.0.aar": (
        "https://dl.google.com/android/maven2/androidx/loader/loader/1.0.0/loader-1.0.0.aar",
        "11f735cb3b55c458d470bed9e25254375b518b4b1bad6926783a7026db0f5025",
        33445,
    ),
    "profileinstaller-1.3.1.aar": (
        "https://dl.google.com/android/maven2/androidx/profileinstaller/profileinstaller/1.3.1/profileinstaller-1.3.1.aar",
        "d0e402ec31f24028a1dc7eb6a0a3f9d9635c1459392cd734396343b73d673948",
        47619,
    ),
    "resourceinspection-annotation-1.0.1.jar": (
        "https://dl.google.com/android/maven2/androidx/resourceinspection/resourceinspection-annotation/1.0.1/resourceinspection-annotation-1.0.1.jar",
        "8cff870ec6fb31db48a52f4a792335b4bf8de07e03bd37823181526433ccd5cb",
        2336,
    ),
    "savedstate-1.2.1.aar": (
        "https://dl.google.com/android/maven2/androidx/savedstate/savedstate/1.2.1/savedstate-1.2.1.aar",
        "21a7d4bcf6bdb94ad7b9283801529300b4fbb8808ca4f191e0cdce6fd8e4705a",
        20217,
    ),
    "startup-runtime-1.1.1.aar": (
        "https://dl.google.com/android/maven2/androidx/startup/startup-runtime/1.1.1/startup-runtime-1.1.1.aar",
        "e0a6329a371262fe4c450372b70fdaf33b769ef6917094723787cfce896b1dd3",
        19371,
    ),
    "tracing-1.0.0.aar": (
        "https://dl.google.com/android/maven2/androidx/tracing/tracing/1.0.0/tracing-1.0.0.aar",
        "07b8b6139665b884a162eccf97891ca50f7f56831233bf25168ae04f7b568612",
        4444,
    ),
    "vectordrawable-1.1.0.aar": (
        "https://dl.google.com/android/maven2/androidx/vectordrawable/vectordrawable/1.1.0/vectordrawable-1.1.0.aar",
        "46fd633ac01b49b7fcabc263bf098c5a8b9e9a69774d234edcca04fb02df8e26",
        33236,
    ),
    "vectordrawable-animated-1.1.0.aar": (
        "https://dl.google.com/android/maven2/androidx/vectordrawable/vectordrawable-animated/1.1.0/vectordrawable-animated-1.1.0.aar",
        "76da2c502371d9c38054df5e2b248d00da87809ed058f3363eae87ce5e2403f8",
        34496,
    ),
    "versionedparcelable-1.1.1.aar": (
        "https://dl.google.com/android/maven2/androidx/versionedparcelable/versionedparcelable/1.1.1/versionedparcelable-1.1.1.aar",
        "57e8d93260d18d5b9007c9eed3c64ad159de90c8609ebfc74a347cbd514535a4",
        31061,
    ),
    "viewpager-1.0.0.aar": (
        "https://dl.google.com/android/maven2/androidx/viewpager/viewpager/1.0.0/viewpager-1.0.0.aar",
        "147af4e14a1984010d8f155e5e19d781f03c1d70dfed02a8e0d18428b8fc8682",
        53513,
    ),
}

[
    http_file(
        name = name,
        sha256 = sha256,
        size_bytes = size_bytes,
        urls = [url],
    )
    for name, (url, sha256, size_bytes) in maven_artifacts.items()
]

filegroup(
    name = "game-activity",
    srcs = [":" + name for name in sorted(maven_artifacts)],
    visibility = ["PUBLIC"],
)

export_file(
    name = "sign.sh",
    visibility = ["PUBLIC"],
)
