load("@root//buck/cargo:defs.bzl", "cargo_binary", "cargo_library", "cargo_test")

srcs = glob(["src/**/*.rs", "src/**/*.qxc"])

cargo_library(srcs = srcs)

cargo_test(srcs = srcs + glob(["samples/**/*.qxc"]))

cargo_binary(srcs = srcs)
