rust_library(
    name = "block-reactive",
    srcs = glob(["src/**/*.rs"]),
    crate = "block_reactive",
    crate_root = "src/lib.rs",
    edition = "2024",
    env = {
        "CARGO_CRATE_NAME": "block_reactive",
        "CARGO_MANIFEST_DIR": "crates/block-reactive",
        "CARGO_PKG_NAME": "block-reactive",
        "CARGO_PKG_VERSION": "0.1.0",
    },
    visibility = ["PUBLIC"],
    deps = [
        "//crates/block-client:block-client",
        "//crates/block:block",
        "//crates/reactive:reactive",
        "//third-party/rust:uuid",
    ],
)

rust_test(
    name = "test",
    srcs = glob(["src/**/*.rs"]),
    crate = "block_reactive",
    crate_root = "src/lib.rs",
    edition = "2024",
    env = {
        "CARGO_CRATE_NAME": "block_reactive",
        "CARGO_MANIFEST_DIR": "crates/block-reactive",
        "CARGO_PKG_NAME": "block-reactive",
        "CARGO_PKG_VERSION": "0.1.0",
    },
    deps = [
        "//crates/block-client:block-client",
        "//crates/block:block",
        "//crates/reactive:reactive",
        "//third-party/rust:uuid",
    ],
)
