[package]
name = "beui-core"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
accesskit = "0.24.1"
foldhash = "0.2"
geometry = { path = "../geometry" }
reactive = { path = "../reactive" }
thumbhash = "0.1"
unicode-segmentation = "1.13"

[lints]
workspace = true
