rust_library(
    name = "game-host",
    crate = "game_host",
    crate_root = "src/lib.rs",
    deps = [
        "//crates/tabletop_games/api:game-api",
        "//third-party/rust:bincode",
        "//third-party/rust:uuid",
        "//third-party/rust:wasmi",
    ],
    edition = "2024",
    env = {
        "CARGO_CRATE_NAME": "game_host",
        "CARGO_MANIFEST_DIR": "crates/tabletop_games/host",
        "CARGO_PKG_NAME": "game-host",
        "CARGO_PKG_VERSION": "0.1.0",
    },
    srcs = glob(["src/**/*.rs"]),
    visibility = ["PUBLIC"],
)

rust_test(
    name = "test",
    crate = "game_host",
    crate_root = "src/lib.rs",
    deps = [
        "//crates/tabletop_games/api:game-api",
        "//third-party/rust:bincode",
        "//third-party/rust:uuid",
        "//third-party/rust:wasmi",
    ],
    edition = "2024",
    env = {
        "CARGO_CRATE_NAME": "game_host",
        "CARGO_MANIFEST_DIR": "crates/tabletop_games/host",
        "CARGO_PKG_NAME": "game-host",
        "CARGO_PKG_VERSION": "0.1.0",
    },
    srcs = glob(["src/**/*.rs"]),
)
