[package]
name = "logic_grid"
edition.workspace = true
version.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
beui = { path = "../../beui", default-features = false, features = ["render"] }
block-editor-beui = { path = "../../block-editor-beui" }
bytemuck = { version = "1", features = ["derive"] }
logicgame = { path = "../../logicgame" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4"] }
wgpu = { version = "29", default-features = false, features = ["std", "wgsl"] }

[dev-dependencies]
block-ui-test = { path = "../../block-ui-test" }

[lints]
workspace = true
