[package]
name = "beui-renderer-wgpu"
edition.workspace = true
version.workspace = true
license.workspace = true

[features]
web = ["dep:web-sys", "wgpu/webgpu", "wgpu/webgl"]

[dependencies]
beui-core = { path = "../beui-core" }
bytemuck = { version = "1", features = ["derive"] }
wgpu = { version = "29", default-features = false, features = ["std", "wgsl"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pollster = "0.4"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", optional = true, features = [
    "CssStyleDeclaration",
    "HtmlCanvasElement",
    "HtmlElement",
] }

[dev-dependencies]
beui-components-unstyled = { path = "../beui-components-unstyled" }
beui-font-freetype = { path = "../beui-font-freetype" }
beui-view = { path = "../beui-view" }
beui_macros = { path = "../beui-macros" }
pollster = "0.4"

[lints]
workspace = true
