[package]
name = "be-client"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
be-block = { path = "../be-block" }
be-commit = { path = "../be-commit" }
be-graph = { path = "../be-graph" }
be-protocol = { path = "../be-protocol" }
be-session = { path = "../be-session" }
be-store = { path = "../be-store" }
futures-util = "0.3"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync", "time"] }
tokio-tungstenite = "0.23"
uuid = { version = "1", features = ["serde", "v4"] }

[dev-dependencies]
be-server = { path = "../be-server" }
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread", "time"] }

[lints]
workspace = true
